### ISSUE TITLE
Support JSON API specification

### ISSUE THREAD

**Issue by aalaap** [obiefy/api-response#13]
It would be good if you could support and promote use of the JSON API specification, which is already an established format:

```
HTTP/1.1 422 Unprocesssable Entity
Content-Type: application/vnd.api+json

{
  "errors": [
    {
      "source": { "pointer": "" },
      "detail":  "Missing `data` Member at document's top level."
    }
  ]
}
```

https://jsonapi.org/examples/

**Comment by obiefy** [comment]
Hi, @aalaap, this package return [Laravel Illuminate JSON Response](https://laravel.com/api/5.8/Illuminate/Http/JsonResponse.html) as result.
it doesn't generate new JSON format. it is just wrapper.

**Comment by obiefy** [comment]
Closed for no-reply.
