### ISSUE TITLE
The API response doesn't set the http status header

### ISSUE THREAD

**Issue by Steve-MP** [obiefy/api-response#16]
It seems that all of your API responses return a 200 OK http status header.

This means that any receiving front-end framework will receive conflicting status information in the event of a non-200 status (JSON object says "500 Internal Server Error", http header says "200 OK") and front-end libraries may fail to detect errors as the status header tells them everything's OK, even if the server has thrown an error.

![Screenshot 2019-09-30 at 17 21 40](https://user-images.githubusercontent.com/13947767/65892612-e35b5280-e3a6-11e9-9076-bb9191d78896.png)

**Comment by SamyOteroGlez** [comment]
Hello @Steve-MP 

There is a config param on `api.php` that is defaulted to false. Set `matchstatus` to true.
```
/*
     * Set the status code from the json response to be the same as the status code
     * in the json response's body.
     */
    'matchstatus' => false,
```
Cheers

**Comment by Steve-MP** [comment]
That seems to work - thanks a lot!
