### ISSUE TITLE
Type cast DATACONT to string

### ISSUE THREAD

**Issue by obiefy** [obiefy/api-response#31]
if the `config('api.stringify')` is set to true response will be like:
```json
{
    "STATUS": "200",
    "MESSAGE": "User Profile data",
    "DATA": [
        ...
    ],
    "DATACOUNT": 6
}
```
The expected response is:
```json
{
    "STATUS": "200",
    "MESSAGE": "User Profile data",
    "DATA": [
        ...
    ],
    "DATACOUNT": "6"
}
```
@beauraines can you please submit PR for this one?

**Comment by beauraines** [comment]
@obiefy Yes, I'll work on this. I have some travel and interviews planned over the next few days, but I will get to this.

**Comment by obiefy** [comment]
Great, Take your time :)
