### ISSUE TITLE
Compatibility with Laravel 8

### ISSUE THREAD

**Issue by tsangaris** [obiefy/api-response#43]
I am trying to install it on Laravel 8.6 but i get:

 Problem 1
    - Installation request for obiefy/api-response ^0.9.1 -> satisfiable by obiefy/api-response[v0.9.1].
    - Conclusion: remove laravel/framework v8.6.0
    - Conclusion: don't install laravel/framework v8.6.0

Any idea if this a compatibility issue with the latest Laravel 8?

**Comment by beauraines** [comment]
@tsangaris There is an open PR for the support to Laravel 8 #42 . Until the PR is merged you can run from that branch. I forked @khatabwedaa and then updated my composer to pull the dependency from my fork.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository


In your composer.json file, you'll change the version of the package, but still source `obiefy/api-response` (this part always gets me) and add the `repositories` array.

**Comment by khatabwedaa** [comment]
@obiefy you have to merge #42 I think 👀

**Comment by obiefy** [comment]
Solved #42 :)
